### ISSUE TITLE
No Value on deploy

### ISSUE THREAD

**Issue by alexsahka** [flic/node-red-contrib-hal#27]
No Value on Node-Red deploy.
Is it possible to keep the last value? Aka Persistent Context.
![image](https://user-images.githubusercontent.com/7469537/138547184-4db23710-df4b-4f68-8f1c-307f8e464a62.png)

**Comment by flic** [comment]
I thought about that but in the end decided to not save state in Node-RED, opting to keep state exclusively in MQTT. I didn't want to end up in a scenario where I keep an extra copy of state information in Node-RED and take action based on possible stale data. I might be reconsidering this in the future, but for the moment it isn't possible.

**Comment by alexsahka** [comment]
When I keep state in MQTT then still there is a short time with - No Value state on deploy.
How to avoid this?

**Comment by flic** [comment]
Make sure that you configure your MQTT devices with retain=true so that the latest value is retained by MQTT. If you have that configured you should get the value pretty much instantly at startup.

**Comment by alexsahka** [comment]
Yes, I keep MQTT devices with retain=true, but there is still a short no value period time about 0.5 to 1 sec long.
I use node-red-contrib-hal for lights logic and lights sometimes turning on/off, need to figure out the trigger delay on deploy.
Thanks.

**Comment by flic** [comment]
Oh okay, I see your point. The short delay never bothered me so I haven't considered it a problem.

**Comment by alexsahka** [comment]
I'm a really heavy user of node-red-contrib-hal. Sometimes I feel addicted...

**Comment by flic** [comment]
That's nice to hear, I thought I was the only user! :) I haven't been able to work on it much for the last year or so, so I'm just glad it holds together!

**Comment by alexsahka** [comment]
Have you ever thought about grouping node-red-contrib-hal: item? For sake of easy finding/sorting?

**Comment by flic** [comment]
I have. I'm also considering if the item object itself should be a lot more advanced, if it would be useful to be able to define multiple characteristics on an item so that the item node itself knows that MQTT topic */relay/0=on means that the first relay is true and */relay/1=off means that the second relay on the same item is false.

I have the beginnings of a new hal2, but I haven't been able to work on it much lately. Maybe later.

**Comment by alexsahka** [comment]
Great news.

**Comment by flic** [comment]
Hey, @alexsahka this might be of interest to you:

https://flows.nodered.org/node/node-red-contrib-hal2

...and yes, it does have persistent storage. ;) 

It's a bit different conceptually than the old one so no guarantees that it fits into your work flow or that you like it, but I think it works a lot better myself. You can use them both in parallel, no collisions. The documentation is still a bit lacking unfortunately, but I published a few examples.

**Comment by alexsahka** [comment]
Thank you! I will try it.
